<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/29 22:31:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=example',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
